import localFont from "next/font/local";
import { Cabin } from 'next/font/google';
import '@fontsource/geist-sans';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const cabin = Cabin({
  subsets: ['latin'],
  variable: '--font-cabin',
  display: 'swap',
});

export const metadata = {
  title: "Squid",
  description: "Generated by create next app",
  icons: {
    icon: "/public/Squid_Logo_Yellow.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cabin.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}